# Generated by Django 5.2.5 on 2025-08-19 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=200)),
                ('latin_name', models.CharField(max_length=200)),
                ('french_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('parent_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='birdapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Sightings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birdapp.bird')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birdapp.location')),
            ],
        ),
    ]
