# Generated by Django 5.2.5 on 2025-08-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='french_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='latin_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
