# Generated by Django 5.2.5 on 2025-08-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0002_alter_bird_french_name_alter_bird_latin_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bird',
            old_name='status',
            new_name='species_status',
        ),
    ]
