# Generated by Django 5.2.5 on 2025-08-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0003_rename_status_bird_species_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sightings',
            old_name='date',
            new_name='date_seen',
        ),
    ]
