# Generated by Django 5.2.5 on 2025-08-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0004_rename_date_sightings_date_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=200)),
                ('subfamily_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
