# Generated by Django 5.2.5 on 2025-08-20 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0005_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='birdapp.family'),
        ),
    ]
