# Generated by Django 5.2.5 on 2025-08-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0006_bird_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='french_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
