# Generated by Django 5.2.5 on 2025-08-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0007_alter_bird_french_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seen', models.DateField()),
                ('count', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birdapp.bird')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birdapp.location')),
            ],
        ),
    ]
