# Generated by Django 5.2.5 on 2025-08-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0008_sighting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sightings',
        ),
    ]
