# Generated by Django 5.2.5 on 2025-08-21 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0010_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='birdapp.trip'),
        ),
    ]
