# Generated by Django 5.2.5 on 2025-08-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0012_trip_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_name']},
        ),
    ]
