# Generated by Django 5.2.5 on 2025-08-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0013_alter_location_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='seen_not_heard',
            field=models.BooleanField(default=False),
        ),
    ]
