# Generated by Django 5.2.5 on 2025-08-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0014_sighting_seen_not_heard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='seen_not_heard',
            new_name='heard_not_seen',
        ),
    ]
